"""Dockerfile generation for paude."""

from __future__ import annotations

from typing import TYPE_CHECKING

from paude.config.models import PaudeConfig
from paude.constants import CONTAINER_ENTRYPOINT, CONTAINER_HOME

TMUX_VERSION = "3.5a"

if TYPE_CHECKING:
    from paude.agents.base import Agent


def _package_install_lines(packages: list[str]) -> list[str]:
    """Generate Dockerfile lines to install OS packages via the detected package manager."""
    pkg_list = " ".join(packages)
    return [
        "",
        "# User-specified packages from paude.json",
        f"""RUN if command -v apt-get >/dev/null 2>&1; then \\
        apt-get update && apt-get install -y {pkg_list} && rm -rf /var/lib/apt/lists/*; \\
    elif command -v apk >/dev/null 2>&1; then \\
        apk add --no-cache {pkg_list}; \\
    elif command -v dnf >/dev/null 2>&1; then \\
        dnf install -y {pkg_list} && dnf clean all; \\
    elif command -v yum >/dev/null 2>&1; then \\
        yum install -y {pkg_list} && yum clean all; \\
    fi""",
    ]


def generate_pip_install_dockerfile(
    config: PaudeConfig,
    include_claude_install: bool = False,
    agent: Agent | None = None,
) -> str:
    """Generate a minimal Dockerfile that layers on a paude base image.

    Use this when layering on top of the default paude image which already has
    entrypoints and all system packages installed.

    Args:
        config: Parsed paude configuration.
        include_claude_install: If True, include Claude Code installation.
            Used for OpenShift remote builds where the base image doesn't have Claude.

    Returns:
        Generated Dockerfile content.
    """
    lines: list[str] = []

    lines.append("# Auto-generated by paude - DO NOT EDIT")
    lines.append("ARG BASE_IMAGE")
    lines.append("FROM ${BASE_IMAGE}")

    # Switch to root for package installation and feature injection
    lines.append("")
    lines.append("# Ensure root for any feature installation")
    lines.append("USER root")

    if config.packages:
        lines.extend(_package_install_lines(config.packages))

    if include_claude_install:
        if agent is None:
            from paude.agents import get_agent

            agent = get_agent("claude")

        lines.extend(agent.dockerfile_install_lines(CONTAINER_HOME))

    lines.append("")
    lines.append("USER paude")
    lines.append(f"WORKDIR {CONTAINER_HOME}")

    return "\n".join(lines)


def generate_workspace_dockerfile(
    config: PaudeConfig,
    agent: Agent | None = None,
) -> str:
    """Generate a Dockerfile that wraps the user's base image with paude requirements.

    This output matches the bash generate_workspace_dockerfile() function exactly.

    Args:
        config: Parsed paude configuration.

    Returns:
        Generated Dockerfile content.
    """
    lines: list[str] = []

    # Header
    lines.append("# Auto-generated by paude - DO NOT EDIT")
    lines.append("ARG BASE_IMAGE")
    lines.append("FROM ${BASE_IMAGE}")

    # Ensure we're running as root for package installation
    # (important for multi-stage builds where stage 1 may end with non-root user)
    lines.append("")
    lines.append("USER root")

    # Add user-specified packages if any (from paude.json "packages" array)
    if config.packages:
        lines.extend(_package_install_lines(config.packages))

    # Standard paude requirements (including tmux for OpenShift session persistence)
    lines.append("")
    lines.append("""# Install required system packages
RUN if command -v apt-get >/dev/null 2>&1; then \\
        apt-get update && \\
        apt-get install -y --no-install-recommends \\
            git curl ca-certificates bash tmux locales socat \\
            coreutils findutils grep sed gawk diffutils less file \\
            tar gzip xz-utils unzip zip && \\
        rm -rf /var/lib/apt/lists/* && \\
        localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8; \\
    elif command -v apk >/dev/null 2>&1; then \\
        apk add --no-cache git curl ca-certificates bash tmux socat \\
            coreutils findutils grep sed gawk diffutils less file \\
            tar gzip xz unzip zip; \\
    elif command -v dnf >/dev/null 2>&1; then \\
        dnf install -y --allowerasing \\
            git curl ca-certificates bash glibc-langpack-en socat \\
            which coreutils findutils grep sed gawk diffutils less file \\
            tar gzip xz unzip zip && \\
        dnf clean all; \\
    elif command -v yum >/dev/null 2>&1; then \\
        yum install -y --allowerasing \\
            git curl ca-certificates bash glibc-langpack-en socat \\
            which coreutils findutils grep sed gawk diffutils less file \\
            tar gzip xz unzip zip && \\
        yum clean all; \\
    else \\
        echo "Warning: Unknown package manager, git may not be available" >&2; \\
    fi""")

    # Build tmux from source on dnf/yum distros (CentOS Stream 10 / RHEL 10
    # distro tmux has a capture-pane -p segfault that crashes the tmux server)
    lines.append("")
    lines.append(f"""ARG TMUX_VERSION={TMUX_VERSION}
RUN if command -v dnf >/dev/null 2>&1 || command -v yum >/dev/null 2>&1; then \\
        PKG_MGR=$(command -v dnf || command -v yum) && \\
        $PKG_MGR install -y gcc make libevent-devel ncurses-devel bison && \\
        curl -fsSL "https://github.com/tmux/tmux/releases/download/${{TMUX_VERSION}}/tmux-${{TMUX_VERSION}}.tar.gz" \\
            -o /tmp/tmux.tar.gz && \\
        tar -xzf /tmp/tmux.tar.gz -C /tmp && \\
        cd /tmp/tmux-${{TMUX_VERSION}} && \\
        ./configure --prefix=/usr/local && \\
        make -j"$(nproc)" && \\
        make install && \\
        rm -rf /tmp/tmux-${{TMUX_VERSION}} /tmp/tmux.tar.gz && \\
        $PKG_MGR remove -y gcc libevent-devel ncurses-devel bison && \\
        $PKG_MGR clean all && \\
        tmux -V; \\
    fi""")

    lines.append("")
    lines.append("""# Install tini init process for zombie reaping
ARG TINI_VERSION=v0.19.0
RUN if ! command -v tini >/dev/null 2>&1; then \\
        ARCH=$(uname -m) && \\
        case "$ARCH" in \\
            x86_64) TINI_ARCH="amd64" ;; \\
            aarch64) TINI_ARCH="arm64" ;; \\
            *) echo "Unsupported architecture for tini: $ARCH" >&2 && exit 1 ;; \\
        esac && \\
        curl -fsSL "https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static-${TINI_ARCH}" \\
            -o /usr/local/bin/tini && \\
        chmod +x /usr/local/bin/tini; \\
    fi && \\
    tini --version""")

    lines.append("")
    lines.append("# Set UTF-8 locale for proper terminal rendering")
    lines.append("ENV LANG=en_US.UTF-8")
    lines.append("ENV LC_ALL=en_US.UTF-8")

    lines.append("")
    lines.append(
        "# Create paude user with root group (GID 0) for OpenShift compatibility"
    )
    lines.append(
        "# OpenShift runs containers with arbitrary UIDs but GID 0, so home must be group-writable"
    )
    if agent is None:
        from paude.agents import get_agent

        agent = get_agent("claude")

    config_dir = agent.config.config_dir_name
    lines.append(
        "RUN (id paude >/dev/null 2>&1 || useradd -M -d /home/paude -s /bin/bash -g 0 paude 2>/dev/null || adduser -D -s /bin/bash -G root paude) && "
        "umask 0002 && "
        f"mkdir -p {CONTAINER_HOME}/{config_dir} {CONTAINER_HOME}/.config {CONTAINER_HOME}/.paude && "
        f"chown -R paude:0 {CONTAINER_HOME}"
    )

    # Copy patch script before agent install lines (agents may RUN it)
    lines.append(
        "COPY --chmod=755 patch-proxy-fetch.sh /usr/local/bin/patch-proxy-fetch.sh"
    )
    lines.append(
        "COPY --chmod=755 patch-openclaw-otel-proxy.sh"
        " /usr/local/bin/patch-openclaw-otel-proxy.sh"
    )
    lines.append(
        "COPY --chmod=755 patch-openclaw-otel-logs.sh"
        " /usr/local/bin/patch-openclaw-otel-logs.sh"
    )

    lines.extend(agent.dockerfile_install_lines(CONTAINER_HOME))

    lines.append("")
    lines.append("# Copy entrypoints and tmux config (requires root)")
    lines.append("USER root")

    lines.append("")
    lines.append(
        "# Preserve base image PATH across login shells (Debian /etc/profile resets PATH)"
    )
    lines.append(
        "RUN echo 'export PATH=\"'\"$PATH\"'\"' > /etc/profile.d/paude-path.sh "
        "&& chmod 644 /etc/profile.d/paude-path.sh"
    )
    lines.append(f"COPY --chmod=755 entrypoint.sh {CONTAINER_ENTRYPOINT}")
    lines.append(
        "COPY --chmod=755 entrypoint-session.sh /usr/local/bin/entrypoint-session.sh"
    )
    lines.append(
        "COPY --chmod=755 entrypoint-lib-credentials.sh"
        " /usr/local/bin/entrypoint-lib-credentials.sh"
    )
    lines.append(
        "COPY --chmod=755 entrypoint-lib-config.sh"
        " /usr/local/bin/entrypoint-lib-config.sh"
    )
    lines.append(
        "COPY --chmod=755 entrypoint-lib-install.sh"
        " /usr/local/bin/entrypoint-lib-install.sh"
    )
    lines.append(
        "COPY --chmod=755 entrypoint-lib-openclaw.sh"
        " /usr/local/bin/entrypoint-lib-openclaw.sh"
    )
    lines.append(f"COPY --chmod=664 tmux.conf {CONTAINER_HOME}/.tmux.conf")

    lines.append("")
    lines.append("USER paude")
    lines.append(f"WORKDIR {CONTAINER_HOME}")
    lines.append(f'ENTRYPOINT ["{CONTAINER_ENTRYPOINT}"]')

    return "\n".join(lines)
